export const GET_GENERAL_INFO = "GET_GENERAL_INFO"
export const GENERAL_INFO_ERROR = "GENERAL_INFO_ERROR"

export const GET_EXPERIENCE = "GET_EXPERIENCE"
export const EXPERIENCE_ERROR = "EXPERIENCE_ERROR"

export const GET_EDUCATION = "GET_EDUCATION"
export const EDUCATION_ERROR = "EDUCATION_ERROR"

export const GET_CERTIFICATE = "GET_CERTIFICATE"
export const CERTIFICATE_ERROR = "CERTIFICATE_ERROR"

export const GET_PROJECT = "GET_PROJECT"
export const PROJECT_ERROR = "PROJECT_ERROR"
